// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace WeddinApp3ML.Model
{
    public class ModelInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("userID"), LoadColumn(1)]
        public string UserID { get; set; }


        [ColumnName("venId"), LoadColumn(2)]
        public string VenId { get; set; }


        [ColumnName("score"), LoadColumn(3)]
        public float Score { get; set; }


    }
}
