// This file was auto-generated by ML.NET Model Builder. 

using System;
using WeddinApp3ML.Model;

namespace WeddinApp3ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                UserID = @"1",
                VenId = @"b80fefe4-935e-46be-98fc-9060db4c2f6f",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Score with predicted Score from sample data...\n\n");
            Console.WriteLine($"UserID: {sampleData.UserID}");
            Console.WriteLine($"VenId: {sampleData.VenId}");
            Console.WriteLine($"\n\nPredicted Score: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
